# Generated by Django 4.1.6 on 2023-02-05 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(default=None, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
