# Generated by Django 4.1.6 on 2023-02-20 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="owner",
        ),
    ]
